### ISSUE TITLE
OBApps crashes on start with wxPython v4.1.1

### ISSUE THREAD

**Issue by gregoirefavre** [gCurse/obapps3#3]
Hello,

I wanted to try it under archlinux :
```
obapps
Traceback (most recent call last):
  File "/sbin/obapps", line 519, in <module>
    main()
  File "/sbin/obapps", line 513, in main
    frame = WLFrame(None, -1, "OBApps3")
  File "/sbin/obapps", line 457, in __init__
    appsel = OBappsel(self, -1, style=wx.BORDER_RAISED, showtitle=False)
  File "/sbin/obapps", line 66, in __init__
    hbox = self._makebuttons(
  File "/sbin/obapps", line 107, in _makebuttons
    hbox.Add(btn, 0, wx.EXPAND | wx.ALIGN_CENTER, wx.ALL, 5)
wx._core.wxAssertionError: C++ assertion "!(flags & (wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL))" failed at /build/python-wxpython/src/wxPython-4.1.1/ext/wxWidgets/src/common/sizer.cpp(2181) in DoInsert(): Vertical alignment flags are ignored with wxEXPAND
```
No idea on how to solve this. Thank you very much.

**Comment by gCurse** [comment]
Thanks for reporting :)

**Comment by gregoirefavre** [comment]
Wouah, that's fast !!! Thank you very much. It works perfectly.
