### ISSUE TITLE
i cant open obapps3

### ISSUE THREAD

**Issue by HqNw** [gCurse/obapps3#4]
every time i try to open it i get this 
[hqnw |~] obapps
10:52:31: Warning: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1014,wx containers,compatible with 2.8),
and wxPython used 3.0 (wchar_t,compiler with C++ ABI 1016,wx containers,compatible with 2.8).
Traceback (most recent call last):
  File "/usr/bin/obapps", line 522, in <module>
    main()
  File "/usr/bin/obapps", line 516, in main
    frame = WLFrame(None, -1, "OBApps3")
  File "/usr/bin/obapps", line 479, in __init__
    path = obaxutils.get_ob_config_path()
  File "/usr/lib/python3.9/site-packages/obaxutils.py", line 38, in get_ob_config_path
    ds = display.Display()
  File "/usr/lib/python3.9/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/python3.9/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/lib/python3.9/site-packages/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'Invalid MIT-MAGIC-COOKIE-1 key'

**Comment by gCurse** [comment]
**"Warning: Mismatch between the program and library build versions detected."** is not the reason for the crash (I get that message too). The program runs fine.

There is something wrong with your X-server: **DisplayConnectionError: Can't connect to display ":0": b'Invalid MIT-MAGIC-COOKIE-1 key'**

Sorry, cannot help you with this.

**Comment by HqNw** [comment]
i solved it and forgot to close the issue my bad 
thanks
